AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless

  SAM template for books application

Resources:
  booksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: books.handler
      Runtime: nodejs14.x
      Events:
        lambdaGetAllBooks:
          Type: Api
          Properties:
            Path: /api/v1/books/
            Method: get
        lambdaGetBook:
          Type: Api
          Properties:
            Path: /api/v1/books/{id}
            Method: get
        lambdaCreateBook:
          Type: Api
          Properties:
            Path: /api/v1/books/
            Method: post
        lambdaCreateComment:
          Type: Api
          Properties:
            Path: /api/v1/books/{id}/comments
            Method: post
        lambdaDeleteComment:
          Type: Api
          Properties:
            Path: /api/v1/books/{id}/comments/{commentId}
            Method: delete
      Policies:
        -   Version: '2012-10-17'
            Statement: 
                -   Effect: Allow
                    Action:
                        -   'dynamodb:Scan'
                        -   'dynamodb:DeleteItem'
                        -   'dynamodb:GetItem'
                        -   'dynamodb:PutItem'
                        -   'dynamodb:UpdateItem'
                    Resource:
                        'Fn::Join':
                            -   ''
                            -   -   'arn:aws:dynamodb:'
                                -   Ref: 'AWS::Region'
                                -   ':'
                                -   Ref: 'AWS::AccountId'
                                -   ':table/books'
  
  booksTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
        TableName: books
        AttributeDefinitions:
            -   AttributeName: id
                AttributeType: S
        KeySchema:
            -   AttributeName: id
                KeyType: HASH
        ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

Outputs:
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BookApi:
    Description: "API Gateway endpoint URL for Prod stage for books function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/books/"
